apiVersion: v2
description: A lightweight, private NPM proxy registry for GKE
name: verdaccio-gke-charts
version: 0.1.0
appVersion: 5.0.4
home: https://xlts-dev.github.io/verdaccio-gke-charts/
icon: https://cdn.verdaccio.dev/logos/default.png
sources:
  - https://verdaccio.org
  - https://github.com/verdaccio/verdaccio
  - https://github.com/xlts-dev/verdaccio-gke-charts
keywords:
  - npm
  - registry
  - javascript
  - nodejs
maintainers:
  - name: splaktar
    email: michael@xlts.dev
